server:
  port: 8585

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
test:
  name: test